return {
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = false,
		build = ":TSUpdate",
		event = { "BufReadPost", "BufNewFile" },
		cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
		opts = {
			indent = { enable = true },
			highlight = { enable = true },
			folds = { enable = true },
			ensure_installed = {
				"bash",
				"dockerfile",
				"diff",
				"hcl",
				"helm",
				"html",
				"javascript",
				"jsdoc",
				"json",
				"jsonc",
				"go",
				"gomod",
				"gowork",
				"gosum",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"ninja",
				"printf",
				"python",
				"query",
				"regex",
				"rst",
				"terraform",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
			},
		},
	},
	{
		"windwp/nvim-ts-autotag",
		opts = {},
	},
}
